#!/usr/bin/env bash 

read -p "Enter Name Of Table :  " nameTable;
until [[ $nameTable =~ ^[a-zA-Z][a-zA-Z0-9] && ! -e $nameTable ]]
do
read -p "Inalid Name Or File Exists :  " nameTable;
done
touch ./$nameTable
touch ./${nameTable}-meta
echo You Create New Table $nameTable

read -p "Enter Number Of Columns In Table :  " numCol;
until [[ $numCol =~ ^[1-9] ]]
do
read -p "Enter Valid Number :  " numCol;
done

for (( i=1;i<$numCol+1;i++ ))
do
read -p "ENTER NAME FOR COLUMN $i :  " name;
match_count=$(grep -o -w "$name" "${nameTable}-meta" | wc -l)
until [[ $name =~ ^[a-zA-Z][a-zA-Z0-9] && $match_count == 0 ]]
do
read -p "Inalid Name Or Name Exists :  " name;
match_count=$(grep -o -w "$name" "${nameTable}-meta" | wc -l)
done
if [[ i -eq $numCol ]]
then
echo -n $name >> ./${nameTable}-meta
else
echo -n $name: >> ./${nameTable}-meta
fi
done



condition=0
echo CHOOCE CONSTRAIN
for (( i=1;i<=$numCol;i++ ))
do

PS3="ENTER NUMBER OF CONSTRAIN FOR COLUMN $i #? "
if [[ $i == 1 ]]
then

		select var in PrimaryKey NonKey
		do
		case $var in
		PrimaryKey)
			constrain="Primary-Key"
			condition=1
			break
			;;
		NonKey)
			constrain="Non-Key"
			break
			;;
		esac
		done 
		echo "" >> ./${nameTable}-meta
		echo -n $constrain: >> ./${nameTable}-meta
elif [[ $condition -eq 1 ]]
then
		constrain="Non-Key"
		if [[ i -eq $numCol ]]
		then
		echo -n $constrain >> ./${nameTable}-meta
		else
		echo -n $constrain: >> ./${nameTable}-meta
		fi
		
		
else
		select var in PrimaryKey NonKey
		do
		case $var in
		"PrimaryKey")
			constrain="Primary-Key"
			condition=1
			break
			;;
		"NonKey")
			constrain="Non-Key"
			break
			;;
		esac
		done 
		if [[ i -eq $numCol ]]
		then
		echo -n $constrain >> ./${nameTable}-meta
		else
		echo -n $constrain: >> ./${nameTable}-meta
		fi
fi
done
echo "" >> ./${nameTable}-meta


for (( i=1;i<=$numCol;i++ ))
do

PS3="ENTER TYPE OF DATA FOR COLUMN $i #? "
		select var in Integer String
		do
		case $var in
		"Integer")
			type="Integer"
			break
			;;
		"String")
			type="String"
			break
			;;
		esac
		done 
		if [[ i -eq $numCol ]]
		then
		echo -n $type >> ./${nameTable}-meta
		else
		echo -n $type: >> ./${nameTable}-meta
		fi
done
echo "" >> ./${nameTable}-meta
echo "TABLE ${nameTable}-meta IS CREATED"
../main
