#!/usr/bin/env bash 
PS3="ENTER NUMBER OF PROCESS#? "
select var in Create-Table List-Tables Drop-Table Insert-into-Table Select-From-Table Delete-From-Table Update-Table Back
do 

case $var in
"Create-Table")	
	../create
	break
	;;
"List-Tables")
	../list
	break
	;;
"Drop-Table")
	../drop
	break
	;;
"Insert-into-Table")
	../insert
	break
	;;
"Select-From-Table")
	../select
	;;
"Delete-From-Table")
	../delete
	break
	;;
"Back")
	../dbms.sh
	break
	;;
"Update-Table")
	../update
	break
	;;
*)
	echo UNKNOWN PROCESS
	;;

esac

done 
